//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.04 at 11:01:54 AM CEST 
//


package com.eds.Converter_Solution.model.input;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eds.Converter_Solution.model.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ThreatModelLinesAKeyValueOfguidanyTypeAValuePropertiesAanyTypeBValueAstring_QNAME = new QName("", "astring");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eds.Converter_Solution.model.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ThreatModel }
     * 
     */
    public ThreatModel createThreatModel() {
        return new ThreatModel();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances }
     * 
     */
    public ThreatModel.ThreatInstances createThreatModelThreatInstances() {
        return new ThreatModel.ThreatInstances();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOB() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValue() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BProperties }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BProperties createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBProperties() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BProperties();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines }
     * 
     */
    public ThreatModel.Lines createThreatModelLines() {
        return new ThreatModel.Lines();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType createThreatModelLinesAKeyValueOfguidanyType() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue createThreatModelLinesAKeyValueOfguidanyTypeAValue() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties createThreatModelLinesAKeyValueOfguidanyTypeAValueProperties() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties.AanyType }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties.AanyType createThreatModelLinesAKeyValueOfguidanyTypeAValuePropertiesAanyType() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties.AanyType();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders }
     * 
     */
    public ThreatModel.Borders createThreatModelBorders() {
        return new ThreatModel.Borders();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType createThreatModelBordersAKeyValueOfguidanyType() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue createThreatModelBordersAKeyValueOfguidanyTypeAValue() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties createThreatModelBordersAKeyValueOfguidanyTypeAValueProperties() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties.AanyType }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties.AanyType createThreatModelBordersAKeyValueOfguidanyTypeAValuePropertiesAanyType() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties.AanyType();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BChangedBy }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BChangedBy createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBChangedBy() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BChangedBy();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BInteractionString }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BInteractionString createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBInteractionString() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BInteractionString();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BStateInformation }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BStateInformation createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBStateInformation() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BStateInformation();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BTitle }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BTitle createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBTitle() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BTitle();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatCategory }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatCategory createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBUserThreatCategory() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatCategory();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatDescription }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatDescription createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBUserThreatDescription() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatDescription();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatShortDescription }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatShortDescription createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBUserThreatShortDescription() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BUserThreatShortDescription();
    }

    /**
     * Create an instance of {@link ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BProperties.AKeyValueOfstringstring }
     * 
     */
    public ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BProperties.AKeyValueOfstringstring createThreatModelThreatInstancesAKeyValueOfstringThreatpcP0PhOBAValueBPropertiesAKeyValueOfstringstring() {
        return new ThreatModel.ThreatInstances.AKeyValueOfstringThreatpcP0PhOB.AValue.BProperties.AKeyValueOfstringstring();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.GenericTypeId }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.GenericTypeId createThreatModelLinesAKeyValueOfguidanyTypeAValueGenericTypeId() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.GenericTypeId();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Guid }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Guid createThreatModelLinesAKeyValueOfguidanyTypeAValueGuid() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Guid();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TypeId }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TypeId createThreatModelLinesAKeyValueOfguidanyTypeAValueTypeId() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TypeId();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.HandleX }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.HandleX createThreatModelLinesAKeyValueOfguidanyTypeAValueHandleX() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.HandleX();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.HandleY }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.HandleY createThreatModelLinesAKeyValueOfguidanyTypeAValueHandleY() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.HandleY();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.PortSource }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.PortSource createThreatModelLinesAKeyValueOfguidanyTypeAValuePortSource() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.PortSource();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.PortTarget }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.PortTarget createThreatModelLinesAKeyValueOfguidanyTypeAValuePortTarget() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.PortTarget();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceGuid }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceGuid createThreatModelLinesAKeyValueOfguidanyTypeAValueSourceGuid() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceGuid();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceX }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceX createThreatModelLinesAKeyValueOfguidanyTypeAValueSourceX() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceX();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceY }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceY createThreatModelLinesAKeyValueOfguidanyTypeAValueSourceY() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.SourceY();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetGuid }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetGuid createThreatModelLinesAKeyValueOfguidanyTypeAValueTargetGuid() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetGuid();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetX }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetX createThreatModelLinesAKeyValueOfguidanyTypeAValueTargetX() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetX();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetY }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetY createThreatModelLinesAKeyValueOfguidanyTypeAValueTargetY() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.TargetY();
    }

    /**
     * Create an instance of {@link ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue }
     * 
     */
    public ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue createThreatModelLinesAKeyValueOfguidanyTypeAValuePropertiesAanyTypeBValue() {
        return new ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.GenericTypeId }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.GenericTypeId createThreatModelBordersAKeyValueOfguidanyTypeAValueGenericTypeId() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.GenericTypeId();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Guid }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Guid createThreatModelBordersAKeyValueOfguidanyTypeAValueGuid() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Guid();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.TypeId }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.TypeId createThreatModelBordersAKeyValueOfguidanyTypeAValueTypeId() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.TypeId();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Height }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Height createThreatModelBordersAKeyValueOfguidanyTypeAValueHeight() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Height();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Left }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Left createThreatModelBordersAKeyValueOfguidanyTypeAValueLeft() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Left();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.StrokeDashArray }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.StrokeDashArray createThreatModelBordersAKeyValueOfguidanyTypeAValueStrokeDashArray() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.StrokeDashArray();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.StrokeThickness }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.StrokeThickness createThreatModelBordersAKeyValueOfguidanyTypeAValueStrokeThickness() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.StrokeThickness();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Top }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Top createThreatModelBordersAKeyValueOfguidanyTypeAValueTop() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Top();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Width }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Width createThreatModelBordersAKeyValueOfguidanyTypeAValueWidth() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Width();
    }

    /**
     * Create an instance of {@link ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue }
     * 
     */
    public ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue createThreatModelBordersAKeyValueOfguidanyTypeAValuePropertiesAanyTypeBValue() {
        return new ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "astring", scope = ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue.class)
    public JAXBElement<String> createThreatModelLinesAKeyValueOfguidanyTypeAValuePropertiesAanyTypeBValueAstring(String value) {
        return new JAXBElement<String>(_ThreatModelLinesAKeyValueOfguidanyTypeAValuePropertiesAanyTypeBValueAstring_QNAME, String.class, ThreatModel.Lines.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "astring", scope = ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue.class)
    public JAXBElement<String> createThreatModelBordersAKeyValueOfguidanyTypeAValuePropertiesAanyTypeBValueAstring(String value) {
        return new JAXBElement<String>(_ThreatModelLinesAKeyValueOfguidanyTypeAValuePropertiesAanyTypeBValueAstring_QNAME, String.class, ThreatModel.Borders.AKeyValueOfguidanyType.AValue.Properties.AanyType.BValue.class, value);
    }

}
