//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.05 at 10:41:57 AM CEST 
//


package com.eds.Converter_Solution.model.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for blockShape complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="blockShape">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.eds.org/eds-schemas}blockShape">
 *       &lt;redefine>
 *         &lt;complexType name="blockShape">
 *           &lt;complexContent>
 *             &lt;extension base="{https://www.eds.org/eds-schemas}shape">
 *               &lt;attribute name="parentSection" type="{https://www.eds.org/eds-schemas}typeIdRef" />
 *             &lt;/extension>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;attGroup ref="{https://www.eds.org/eds-schemas}additionalSectionProperties"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "blockShape")
@XmlSeeAlso({
    com.eds.Converter_Solution.model.output.Diagram.Sections.InternetDmz.class,
    com.eds.Converter_Solution.model.output.Diagram.Sections.CompanyTrustSection.class,
    com.eds.Converter_Solution.model.output.Diagram.Sections.SandboxTrustSection.class
})
public class BlockShape
    extends OriginalBlockShape
{


}
