//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.05 at 10:41:57 AM CEST 
//


package com.eds.Converter_Solution.model.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for externalEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="externalEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.eds.org/eds-schemas}externalEntity">
 *       &lt;redefine>
 *         &lt;complexType name="externalEntity">
 *           &lt;complexContent>
 *             &lt;extension base="{https://www.eds.org/eds-schemas}blockElement">
 *               &lt;attribute name="sanitizeInput" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;attribute name="sanitizeOutput" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;attribute name="isThreadSafe" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *             &lt;/extension>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;attGroup ref="{https://www.eds.org/eds-schemas}additionalExternalEntityProperties"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "externalEntity")
@XmlSeeAlso({
    com.eds.Converter_Solution.model.output.Diagram.Elements.Browser.class,
    com.eds.Converter_Solution.model.output.Diagram.Elements.ExternalWebApplication.class,
    com.eds.Converter_Solution.model.output.Diagram.Elements.ExternalWebService.class
})
public class ExternalEntity
    extends OriginalExternalEntity
{


}
