//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.05 at 10:41:57 AM CEST 
//


package com.eds.Converter_Solution.model.output;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eds.Converter_Solution.model.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DiagramElementsCloudStorage_QNAME = new QName("https://www.eds.org/eds-schemas", "cloudStorage");
    private final static QName _DiagramElementsNoSqlDatabase_QNAME = new QName("https://www.eds.org/eds-schemas", "noSqlDatabase");
    private final static QName _DiagramElementsSpecialApplication_QNAME = new QName("https://www.eds.org/eds-schemas", "specialApplication");
    private final static QName _DiagramElementsExternalWebApplication_QNAME = new QName("https://www.eds.org/eds-schemas", "externalWebApplication");
    private final static QName _DiagramElementsWebApplication_QNAME = new QName("https://www.eds.org/eds-schemas", "webApplication");
    private final static QName _DiagramElementsWebServer_QNAME = new QName("https://www.eds.org/eds-schemas", "webServer");
    private final static QName _DiagramElementsThickClient_QNAME = new QName("https://www.eds.org/eds-schemas", "thickClient");
    private final static QName _DiagramElementsSmartPhone_QNAME = new QName("https://www.eds.org/eds-schemas", "smartPhone");
    private final static QName _DiagramElementsFileSystem_QNAME = new QName("https://www.eds.org/eds-schemas", "fileSystem");
    private final static QName _DiagramElementsHtml5LocalStorage_QNAME = new QName("https://www.eds.org/eds-schemas", "html5LocalStorage");
    private final static QName _DiagramElementsSqlDatabase_QNAME = new QName("https://www.eds.org/eds-schemas", "sqlDatabase");
    private final static QName _DiagramElementsSecurityGateway_QNAME = new QName("https://www.eds.org/eds-schemas", "securityGateway");
    private final static QName _DiagramElementsCache_QNAME = new QName("https://www.eds.org/eds-schemas", "cache");
    private final static QName _DiagramElementsUser_QNAME = new QName("https://www.eds.org/eds-schemas", "user");
    private final static QName _DiagramElementsAuthorizedProvider_QNAME = new QName("https://www.eds.org/eds-schemas", "authorizedProvider");
    private final static QName _DiagramElementsManagedApplication_QNAME = new QName("https://www.eds.org/eds-schemas", "managedApplication");
    private final static QName _DiagramElementsExternalWebService_QNAME = new QName("https://www.eds.org/eds-schemas", "externalWebService");
    private final static QName _DiagramElementsConfigurationFile_QNAME = new QName("https://www.eds.org/eds-schemas", "configurationFile");
    private final static QName _DiagramElementsLogFile_QNAME = new QName("https://www.eds.org/eds-schemas", "logFile");
    private final static QName _DiagramElementsBrowser_QNAME = new QName("https://www.eds.org/eds-schemas", "browser");
    private final static QName _DiagramElementsWebService_QNAME = new QName("https://www.eds.org/eds-schemas", "webService");
    private final static QName _DiagramFlowsSsl_QNAME = new QName("https://www.eds.org/eds-schemas", "ssl");
    private final static QName _DiagramFlowsSql_QNAME = new QName("https://www.eds.org/eds-schemas", "sql");
    private final static QName _DiagramFlowsRpcOrDcom_QNAME = new QName("https://www.eds.org/eds-schemas", "rpcOrDcom");
    private final static QName _DiagramFlowsHttp_QNAME = new QName("https://www.eds.org/eds-schemas", "http");
    private final static QName _DiagramFlowsSmb_QNAME = new QName("https://www.eds.org/eds-schemas", "smb");
    private final static QName _DiagramFlowsHttps_QNAME = new QName("https://www.eds.org/eds-schemas", "https");
    private final static QName _DiagramFlowsBinary_QNAME = new QName("https://www.eds.org/eds-schemas", "binary");
    private final static QName _DiagramFlowsNamedPipe_QNAME = new QName("https://www.eds.org/eds-schemas", "namedPipe");
    private final static QName _DiagramFlowsIpSec_QNAME = new QName("https://www.eds.org/eds-schemas", "ipSec");
    private final static QName _DiagramFlowsTcp_QNAME = new QName("https://www.eds.org/eds-schemas", "tcp");
    private final static QName _DiagramFlowsUdp_QNAME = new QName("https://www.eds.org/eds-schemas", "udp");
    private final static QName _DiagramSectionsOfficeNetwork_QNAME = new QName("https://www.eds.org/eds-schemas", "officeNetwork");
    private final static QName _DiagramSectionsSandboxTrustSection_QNAME = new QName("https://www.eds.org/eds-schemas", "sandboxTrustSection");
    private final static QName _DiagramSectionsSharedNetwork_QNAME = new QName("https://www.eds.org/eds-schemas", "sharedNetwork");
    private final static QName _DiagramSectionsInternetDmz_QNAME = new QName("https://www.eds.org/eds-schemas", "internetDmz");
    private final static QName _DiagramSectionsOtherTrustSection_QNAME = new QName("https://www.eds.org/eds-schemas", "otherTrustSection");
    private final static QName _DiagramSectionsCompanyTrustSection_QNAME = new QName("https://www.eds.org/eds-schemas", "companyTrustSection");
    private final static QName _DiagramBoundariesMachineBoundary_QNAME = new QName("https://www.eds.org/eds-schemas", "machineBoundary");
    private final static QName _DiagramBoundariesInternetBoundary_QNAME = new QName("https://www.eds.org/eds-schemas", "internetBoundary");
    private final static QName _DiagramBoundariesAppContainerBoundary_QNAME = new QName("https://www.eds.org/eds-schemas", "appContainerBoundary");
    private final static QName _DiagramBoundariesLocalDMZBoundary_QNAME = new QName("https://www.eds.org/eds-schemas", "localDMZBoundary");
    private final static QName _StringAndLinkLink_QNAME = new QName("https://www.eds.org/eds-schemas", "link");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eds.Converter_Solution.model.output
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Diagram }
     * 
     */
    public Diagram createDiagram() {
        return new Diagram();
    }

    /**
     * Create an instance of {@link OriginalFlow }
     * 
     */
    public OriginalFlow createOriginalFlow() {
        return new OriginalFlow();
    }

    /**
     * Create an instance of {@link OriginalFlow.BoundariesCrossed }
     * 
     */
    public OriginalFlow.BoundariesCrossed createOriginalFlowBoundariesCrossed() {
        return new OriginalFlow.BoundariesCrossed();
    }

    /**
     * Create an instance of {@link Assets }
     * 
     */
    public Assets createAssets() {
        return new Assets();
    }

    /**
     * Create an instance of {@link Exploits }
     * 
     */
    public Exploits createExploits() {
        return new Exploits();
    }

    /**
     * Create an instance of {@link StringAndLink }
     * 
     */
    public StringAndLink createStringAndLink() {
        return new StringAndLink();
    }

    /**
     * Create an instance of {@link Diagram.Sections }
     * 
     */
    public Diagram.Sections createDiagramSections() {
        return new Diagram.Sections();
    }

    /**
     * Create an instance of {@link Diagram.Boundaries }
     * 
     */
    public Diagram.Boundaries createDiagramBoundaries() {
        return new Diagram.Boundaries();
    }

    /**
     * Create an instance of {@link Diagram.Flows }
     * 
     */
    public Diagram.Flows createDiagramFlows() {
        return new Diagram.Flows();
    }

    /**
     * Create an instance of {@link Diagram.Elements }
     * 
     */
    public Diagram.Elements createDiagramElements() {
        return new Diagram.Elements();
    }

    /**
     * Create an instance of {@link ExploitDefinitions }
     * 
     */
    public ExploitDefinitions createExploitDefinitions() {
        return new ExploitDefinitions();
    }

    /**
     * Create an instance of {@link ExploitDefinition }
     * 
     */
    public ExploitDefinition createExploitDefinition() {
        return new ExploitDefinition();
    }

    /**
     * Create an instance of {@link AssetDefinitions }
     * 
     */
    public AssetDefinitions createAssetDefinitions() {
        return new AssetDefinitions();
    }

    /**
     * Create an instance of {@link AssetDefinition }
     * 
     */
    public AssetDefinition createAssetDefinition() {
        return new AssetDefinition();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Shape }
     * 
     */
    public Shape createShape() {
        return new Shape();
    }

    /**
     * Create an instance of {@link ImportAssets }
     * 
     */
    public ImportAssets createImportAssets() {
        return new ImportAssets();
    }

    /**
     * Create an instance of {@link BlockShape }
     * 
     */
    public BlockShape createBlockShape() {
        return new BlockShape();
    }

    /**
     * Create an instance of {@link ImportExploits }
     * 
     */
    public ImportExploits createImportExploits() {
        return new ImportExploits();
    }

    /**
     * Create an instance of {@link ExternalEntity }
     * 
     */
    public ExternalEntity createExternalEntity() {
        return new ExternalEntity();
    }

    /**
     * Create an instance of {@link DataStore }
     * 
     */
    public DataStore createDataStore() {
        return new DataStore();
    }

    /**
     * Create an instance of {@link ExploitDefinitionReport }
     * 
     */
    public ExploitDefinitionReport createExploitDefinitionReport() {
        return new ExploitDefinitionReport();
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link OriginalFlow.BoundariesCrossed.BoundaryCross }
     * 
     */
    public OriginalFlow.BoundariesCrossed.BoundaryCross createOriginalFlowBoundariesCrossedBoundaryCross() {
        return new OriginalFlow.BoundariesCrossed.BoundaryCross();
    }

    /**
     * Create an instance of {@link OriginalDataStore }
     * 
     */
    public OriginalDataStore createOriginalDataStore() {
        return new OriginalDataStore();
    }

    /**
     * Create an instance of {@link OriginalExternalEntity }
     * 
     */
    public OriginalExternalEntity createOriginalExternalEntity() {
        return new OriginalExternalEntity();
    }

    /**
     * Create an instance of {@link OriginalBlockShape }
     * 
     */
    public OriginalBlockShape createOriginalBlockShape() {
        return new OriginalBlockShape();
    }

    /**
     * Create an instance of {@link OriginalShape }
     * 
     */
    public OriginalShape createOriginalShape() {
        return new OriginalShape();
    }

    /**
     * Create an instance of {@link Assets.Asset }
     * 
     */
    public Assets.Asset createAssetsAsset() {
        return new Assets.Asset();
    }

    /**
     * Create an instance of {@link Exploits.Exploit }
     * 
     */
    public Exploits.Exploit createExploitsExploit() {
        return new Exploits.Exploit();
    }

    /**
     * Create an instance of {@link OriginalProcess }
     * 
     */
    public OriginalProcess createOriginalProcess() {
        return new OriginalProcess();
    }

    /**
     * Create an instance of {@link StringAndLink.Link }
     * 
     */
    public StringAndLink.Link createStringAndLinkLink() {
        return new StringAndLink.Link();
    }

    /**
     * Create an instance of {@link Diagram.Sections.InternetDmz }
     * 
     */
    public Diagram.Sections.InternetDmz createDiagramSectionsInternetDmz() {
        return new Diagram.Sections.InternetDmz();
    }

    /**
     * Create an instance of {@link Diagram.Sections.CompanyTrustSection }
     * 
     */
    public Diagram.Sections.CompanyTrustSection createDiagramSectionsCompanyTrustSection() {
        return new Diagram.Sections.CompanyTrustSection();
    }

    /**
     * Create an instance of {@link Diagram.Sections.SandboxTrustSection }
     * 
     */
    public Diagram.Sections.SandboxTrustSection createDiagramSectionsSandboxTrustSection() {
        return new Diagram.Sections.SandboxTrustSection();
    }

    /**
     * Create an instance of {@link Diagram.Boundaries.InternetBoundary }
     * 
     */
    public Diagram.Boundaries.InternetBoundary createDiagramBoundariesInternetBoundary() {
        return new Diagram.Boundaries.InternetBoundary();
    }

    /**
     * Create an instance of {@link Diagram.Boundaries.MachineBoundary }
     * 
     */
    public Diagram.Boundaries.MachineBoundary createDiagramBoundariesMachineBoundary() {
        return new Diagram.Boundaries.MachineBoundary();
    }

    /**
     * Create an instance of {@link Diagram.Flows.Binary }
     * 
     */
    public Diagram.Flows.Binary createDiagramFlowsBinary() {
        return new Diagram.Flows.Binary();
    }

    /**
     * Create an instance of {@link Diagram.Flows.Http }
     * 
     */
    public Diagram.Flows.Http createDiagramFlowsHttp() {
        return new Diagram.Flows.Http();
    }

    /**
     * Create an instance of {@link Diagram.Flows.Https }
     * 
     */
    public Diagram.Flows.Https createDiagramFlowsHttps() {
        return new Diagram.Flows.Https();
    }

    /**
     * Create an instance of {@link Diagram.Elements.WebApplication }
     * 
     */
    public Diagram.Elements.WebApplication createDiagramElementsWebApplication() {
        return new Diagram.Elements.WebApplication();
    }

    /**
     * Create an instance of {@link Diagram.Elements.WebService }
     * 
     */
    public Diagram.Elements.WebService createDiagramElementsWebService() {
        return new Diagram.Elements.WebService();
    }

    /**
     * Create an instance of {@link Diagram.Elements.WebServer }
     * 
     */
    public Diagram.Elements.WebServer createDiagramElementsWebServer() {
        return new Diagram.Elements.WebServer();
    }

    /**
     * Create an instance of {@link Diagram.Elements.ThickClient }
     * 
     */
    public Diagram.Elements.ThickClient createDiagramElementsThickClient() {
        return new Diagram.Elements.ThickClient();
    }

    /**
     * Create an instance of {@link Diagram.Elements.CloudStorage }
     * 
     */
    public Diagram.Elements.CloudStorage createDiagramElementsCloudStorage() {
        return new Diagram.Elements.CloudStorage();
    }

    /**
     * Create an instance of {@link Diagram.Elements.SqlDatabase }
     * 
     */
    public Diagram.Elements.SqlDatabase createDiagramElementsSqlDatabase() {
        return new Diagram.Elements.SqlDatabase();
    }

    /**
     * Create an instance of {@link Diagram.Elements.NoSqlDatabase }
     * 
     */
    public Diagram.Elements.NoSqlDatabase createDiagramElementsNoSqlDatabase() {
        return new Diagram.Elements.NoSqlDatabase();
    }

    /**
     * Create an instance of {@link Diagram.Elements.FileSystem }
     * 
     */
    public Diagram.Elements.FileSystem createDiagramElementsFileSystem() {
        return new Diagram.Elements.FileSystem();
    }

    /**
     * Create an instance of {@link Diagram.Elements.LogFile }
     * 
     */
    public Diagram.Elements.LogFile createDiagramElementsLogFile() {
        return new Diagram.Elements.LogFile();
    }

    /**
     * Create an instance of {@link Diagram.Elements.Browser }
     * 
     */
    public Diagram.Elements.Browser createDiagramElementsBrowser() {
        return new Diagram.Elements.Browser();
    }

    /**
     * Create an instance of {@link Diagram.Elements.ExternalWebApplication }
     * 
     */
    public Diagram.Elements.ExternalWebApplication createDiagramElementsExternalWebApplication() {
        return new Diagram.Elements.ExternalWebApplication();
    }

    /**
     * Create an instance of {@link Diagram.Elements.ExternalWebService }
     * 
     */
    public Diagram.Elements.ExternalWebService createDiagramElementsExternalWebService() {
        return new Diagram.Elements.ExternalWebService();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.CloudStorage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "cloudStorage", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.CloudStorage> createDiagramElementsCloudStorage(Diagram.Elements.CloudStorage value) {
        return new JAXBElement<Diagram.Elements.CloudStorage>(_DiagramElementsCloudStorage_QNAME, Diagram.Elements.CloudStorage.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.NoSqlDatabase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "noSqlDatabase", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.NoSqlDatabase> createDiagramElementsNoSqlDatabase(Diagram.Elements.NoSqlDatabase value) {
        return new JAXBElement<Diagram.Elements.NoSqlDatabase>(_DiagramElementsNoSqlDatabase_QNAME, Diagram.Elements.NoSqlDatabase.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "specialApplication", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsSpecialApplication(Process value) {
        return new JAXBElement<Process>(_DiagramElementsSpecialApplication_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.ExternalWebApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "externalWebApplication", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.ExternalWebApplication> createDiagramElementsExternalWebApplication(Diagram.Elements.ExternalWebApplication value) {
        return new JAXBElement<Diagram.Elements.ExternalWebApplication>(_DiagramElementsExternalWebApplication_QNAME, Diagram.Elements.ExternalWebApplication.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.WebApplication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "webApplication", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.WebApplication> createDiagramElementsWebApplication(Diagram.Elements.WebApplication value) {
        return new JAXBElement<Diagram.Elements.WebApplication>(_DiagramElementsWebApplication_QNAME, Diagram.Elements.WebApplication.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.WebServer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "webServer", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.WebServer> createDiagramElementsWebServer(Diagram.Elements.WebServer value) {
        return new JAXBElement<Diagram.Elements.WebServer>(_DiagramElementsWebServer_QNAME, Diagram.Elements.WebServer.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.ThickClient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "thickClient", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.ThickClient> createDiagramElementsThickClient(Diagram.Elements.ThickClient value) {
        return new JAXBElement<Diagram.Elements.ThickClient>(_DiagramElementsThickClient_QNAME, Diagram.Elements.ThickClient.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "smartPhone", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsSmartPhone(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsSmartPhone_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.FileSystem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "fileSystem", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.FileSystem> createDiagramElementsFileSystem(Diagram.Elements.FileSystem value) {
        return new JAXBElement<Diagram.Elements.FileSystem>(_DiagramElementsFileSystem_QNAME, Diagram.Elements.FileSystem.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "html5LocalStorage", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsHtml5LocalStorage(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsHtml5LocalStorage_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.SqlDatabase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "sqlDatabase", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.SqlDatabase> createDiagramElementsSqlDatabase(Diagram.Elements.SqlDatabase value) {
        return new JAXBElement<Diagram.Elements.SqlDatabase>(_DiagramElementsSqlDatabase_QNAME, Diagram.Elements.SqlDatabase.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "securityGateway", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsSecurityGateway(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsSecurityGateway_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "cache", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsCache(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsCache_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "user", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsUser(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsUser_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "authorizedProvider", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsAuthorizedProvider(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsAuthorizedProvider_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "managedApplication", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsManagedApplication(Process value) {
        return new JAXBElement<Process>(_DiagramElementsManagedApplication_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.ExternalWebService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "externalWebService", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.ExternalWebService> createDiagramElementsExternalWebService(Diagram.Elements.ExternalWebService value) {
        return new JAXBElement<Diagram.Elements.ExternalWebService>(_DiagramElementsExternalWebService_QNAME, Diagram.Elements.ExternalWebService.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "configurationFile", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsConfigurationFile(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsConfigurationFile_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.LogFile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "logFile", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.LogFile> createDiagramElementsLogFile(Diagram.Elements.LogFile value) {
        return new JAXBElement<Diagram.Elements.LogFile>(_DiagramElementsLogFile_QNAME, Diagram.Elements.LogFile.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.Browser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "browser", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.Browser> createDiagramElementsBrowser(Diagram.Elements.Browser value) {
        return new JAXBElement<Diagram.Elements.Browser>(_DiagramElementsBrowser_QNAME, Diagram.Elements.Browser.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.WebService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "webService", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.WebService> createDiagramElementsWebService(Diagram.Elements.WebService value) {
        return new JAXBElement<Diagram.Elements.WebService>(_DiagramElementsWebService_QNAME, Diagram.Elements.WebService.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "ssl", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSsl(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSsl_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "sql", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSql(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSql_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "rpcOrDcom", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsRpcOrDcom(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsRpcOrDcom_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Flows.Http }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "http", scope = Diagram.Flows.class)
    public JAXBElement<Diagram.Flows.Http> createDiagramFlowsHttp(Diagram.Flows.Http value) {
        return new JAXBElement<Diagram.Flows.Http>(_DiagramFlowsHttp_QNAME, Diagram.Flows.Http.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "smb", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSmb(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSmb_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Flows.Https }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "https", scope = Diagram.Flows.class)
    public JAXBElement<Diagram.Flows.Https> createDiagramFlowsHttps(Diagram.Flows.Https value) {
        return new JAXBElement<Diagram.Flows.Https>(_DiagramFlowsHttps_QNAME, Diagram.Flows.Https.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Flows.Binary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "binary", scope = Diagram.Flows.class)
    public JAXBElement<Diagram.Flows.Binary> createDiagramFlowsBinary(Diagram.Flows.Binary value) {
        return new JAXBElement<Diagram.Flows.Binary>(_DiagramFlowsBinary_QNAME, Diagram.Flows.Binary.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "namedPipe", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsNamedPipe(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsNamedPipe_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "ipSec", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsIpSec(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsIpSec_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "tcp", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsTcp(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsTcp_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "udp", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsUdp(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsUdp_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "officeNetwork", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsOfficeNetwork(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsOfficeNetwork_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Sections.SandboxTrustSection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "sandboxTrustSection", scope = Diagram.Sections.class)
    public JAXBElement<Diagram.Sections.SandboxTrustSection> createDiagramSectionsSandboxTrustSection(Diagram.Sections.SandboxTrustSection value) {
        return new JAXBElement<Diagram.Sections.SandboxTrustSection>(_DiagramSectionsSandboxTrustSection_QNAME, Diagram.Sections.SandboxTrustSection.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "sharedNetwork", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsSharedNetwork(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsSharedNetwork_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Sections.InternetDmz }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "internetDmz", scope = Diagram.Sections.class)
    public JAXBElement<Diagram.Sections.InternetDmz> createDiagramSectionsInternetDmz(Diagram.Sections.InternetDmz value) {
        return new JAXBElement<Diagram.Sections.InternetDmz>(_DiagramSectionsInternetDmz_QNAME, Diagram.Sections.InternetDmz.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "otherTrustSection", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsOtherTrustSection(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsOtherTrustSection_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Sections.CompanyTrustSection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "companyTrustSection", scope = Diagram.Sections.class)
    public JAXBElement<Diagram.Sections.CompanyTrustSection> createDiagramSectionsCompanyTrustSection(Diagram.Sections.CompanyTrustSection value) {
        return new JAXBElement<Diagram.Sections.CompanyTrustSection>(_DiagramSectionsCompanyTrustSection_QNAME, Diagram.Sections.CompanyTrustSection.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Boundaries.MachineBoundary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "machineBoundary", scope = Diagram.Boundaries.class)
    public JAXBElement<Diagram.Boundaries.MachineBoundary> createDiagramBoundariesMachineBoundary(Diagram.Boundaries.MachineBoundary value) {
        return new JAXBElement<Diagram.Boundaries.MachineBoundary>(_DiagramBoundariesMachineBoundary_QNAME, Diagram.Boundaries.MachineBoundary.class, Diagram.Boundaries.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Boundaries.InternetBoundary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "internetBoundary", scope = Diagram.Boundaries.class)
    public JAXBElement<Diagram.Boundaries.InternetBoundary> createDiagramBoundariesInternetBoundary(Diagram.Boundaries.InternetBoundary value) {
        return new JAXBElement<Diagram.Boundaries.InternetBoundary>(_DiagramBoundariesInternetBoundary_QNAME, Diagram.Boundaries.InternetBoundary.class, Diagram.Boundaries.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "appContainerBoundary", scope = Diagram.Boundaries.class)
    public JAXBElement<Shape> createDiagramBoundariesAppContainerBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramBoundariesAppContainerBoundary_QNAME, Shape.class, Diagram.Boundaries.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "localDMZBoundary", scope = Diagram.Boundaries.class)
    public JAXBElement<Shape> createDiagramBoundariesLocalDMZBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramBoundariesLocalDMZBoundary_QNAME, Shape.class, Diagram.Boundaries.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringAndLink.Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.eds.org/eds-schemas", name = "link", scope = StringAndLink.class)
    public JAXBElement<StringAndLink.Link> createStringAndLinkLink(StringAndLink.Link value) {
        return new JAXBElement<StringAndLink.Link>(_StringAndLinkLink_QNAME, StringAndLink.Link.class, StringAndLink.class, value);
    }

}
